### ISSUE TITLE
Cannot access class 'com.haroldadmin.cnradapter.NetworkResponse'.

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [haroldadmin/NetworkResponseAdapter#1]
Cannot access class 'com.haroldadmin.cnradapter.NetworkResponse'. Check your module classpath for missing or conflicting dependencies.

**Comment by haroldadmin** [comment]
Can you add more information regarding the error? A `build.gradle` config file would be great!

**Comment by JavierSegoviaCordoba** [comment]
This is all the info I have. Really the classes are imported, the error is there anyway.
![image](https://user-images.githubusercontent.com/7463564/61995443-01e05d00-b089-11e9-9982-54215819a3ae.png)
```
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.5.0-rc01'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.41"
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:2.1.0-beta02"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

**Comment by haroldadmin** [comment]
I just realized that the artifact coordinates in the README file are incorrect. I updated the repository name a little while back but forgot to update the readme file. Are you using the following dependency: `com.github.haroldadmin:NetworkResponseAdapter:2.0.2` ?

I'll push out a fix in a some time.

**Comment by JavierSegoviaCordoba** [comment]
Both dependencies have the same problem for me. Invalidating caches doesn't work too

**Comment by JavierSegoviaCordoba** [comment]
@haroldadmin can you mention me when the fix is out please?

**Comment by haroldadmin** [comment]
I am looking into the issue right now. Trying to reproduce it on my system. If I can't reproduce it, would you consider making a small repository/project which i can use to reproduce the issue?

**Comment by JavierSegoviaCordoba** [comment]
Take a look at your email, I can share via Telegram for example

**Comment by JavierSegoviaCordoba** [comment]
I think I fixed it, I was accessing the classes from a module without the dependency, but Android Studio was letting me to import them... thank you for your help!
