### ISSUE TITLE
204 No Content count as ServerError

### ISSUE THREAD

**Issue by foohwa** [haroldadmin/NetworkResponseAdapter#19]
i am testing a loginApi, if user is not existed, it will return 204 no content. it supposed to be success response but it was fall under ServerError, do you know whats the issue here? 

![image](https://user-images.githubusercontent.com/50357612/86329156-5c5e4200-bc78-11ea-8a22-7dacb960cc52.png)

**Comment by haroldadmin** [comment]
Hi! Not sure if you still need help with this, but the reason why you are getting a `ServerError` on a 204 response code is that response body is null.

Empty bodies are kind of a special case. To make sure that this response gets classified as a `Success`, use `Unit` as the success type in `NetworkResponse`.

```kotlin
@GET("login")
suspend fun login(): NetworkResponse<Unit, Error>
```

**Comment by foohwa** [comment]
Hi @haroldadmin thanks for replying my post. I have closed it because i saw the previous PR already ahha. Btw i have one more question too, what if i want to get the response of the api too? its actually a login api, if api return 204 then the user is not registered, if success it return 200 and a response body

**Comment by haroldadmin** [comment]
The `NetworkResponse` class can not be generic on multiple success types, and therefore there is no simple solution to your problem. You could look into using [moshi-sealed](https://github.com/ZacSweers/moshi-sealed) though. I have never tried it with NetworkResponseAdapter though, so I can not say if it will work or not.

**Comment by haroldadmin** [comment]
If you would like to open a discussion on usage of moshi-sealed with this library, please open a separate issue :)
