### ISSUE TITLE
Empty body on certain server errors

### ISSUE THREAD

**Issue by ZiadLattoufSoffa** [haroldadmin/NetworkResponseAdapter#20]
I have some server errors that return empty bodies and the others return an error. Is there a way to handle this without returning a body on all my server errors ?

**Comment by haroldadmin** [comment]
For errors which return a body, you can use `NetworkResponse` as usual.

For errors which do not return a body, it depends on what the `Content-Type` header value is. If the body is a string, then use [Retrofit Scalars Converter](https://github.com/square/retrofit/tree/master/retrofit-converters/scalars) and declare your error type as `String`

  ```kotlin
  val retrofit = Retrofit.Builder()
        .addCallAdapterFactory(NetworkResponseAdapterFactory())
        .addConverterFactory(ScalarsConverterFactory.create())
  ...
  
  suspend fun response(): NetworkResponse<Success, String>
  ```
