### ISSUE TITLE
HTTP 204 No Content success status response code

### ISSUE THREAD

**Issue by Sideness** [haroldadmin/NetworkResponseAdapter#21]
Hello,
When doing a PUT request, a lot of servers respond with a 204 no-content, considered by your library as a ServerError. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204
Do you think you could change that to SUCCESS?
Thanks a lot and have a nice day.

**Comment by haroldadmin** [comment]
Empty bodies are handled as a special case by the library. Please use `Unit` as the success type for the endpoints where you receive an empty response.

**Comment by Sideness** [comment]
Oops sorry, I didn't know. Thanks for the tip!
Have a nice day.
