### ISSUE TITLE
Code 302 (Found after redirect) results in UnknownError + No chance to get header and body of the response.

### ISSUE THREAD

**Issue by szsoftware** [haroldadmin/NetworkResponseAdapter#25]
https://github.com/haroldadmin/NetworkResponseAdapter/blob/76c3ae415dffbab45fe19e032800a00755d77603/src/main/kotlin/com/haroldadmin/cnradapter/ResponseHandler.kt#L37

This is a dependent issue to:
https://github.com/square/okhttp/issues/6456

Workaround: ResonseCodeInterceptor(302, 200)

    /**
     * @author szsoftware
     */
    class ResponseCodeInterceptor(private val from: Int, private val to: Int) : Interceptor {
        @Throws(IOException::class)
        override fun intercept(chain: Interceptor.Chain): Response {
            val request = chain.request()
            val response = chain.proceed(request)
            val headers = response.headers
            val body = response.body

            val newCode = when(val oldCode = response.code) { from -> to else -> oldCode}

            return response
                    .newBuilder()
                    .code(newCode)
                    .headers(headers)
                    .body(body)
                    .build()
        }
    }

In my case I even only needed the headers, since the response body is empty (as expected).
In the responses header, in a Location "field" resides a token which was requested by a previous post request.
Due to sso mechanisms, a ridiculous 303 chain resulted in 302 at the end, what could finally not been processed by Retrofit + NetworkResponseAdapter.

**Comment by haroldadmin** [comment]
Thanks for reporting the issue. This seems like an extension of #23 where information about the response is lost in `NetworkResponse.UnknownError`. The plan is to add nullable fields to the UnknownError type containing information about the response, such as headers or the raw response itself.

I can not give you an ETA on this, unfortunately. I would be happy to accept external contributions, though.
