### ISSUE TITLE
NetworkResponse.ServerError: returns null message

### ISSUE THREAD

**Issue by panchalamitr** [haroldadmin/NetworkResponseAdapter#28]
API send response when there is any error, like below

`{"message":"Missing Authentication Token"}`

To handle an error, I have made below class

`data class ErrorImages(@SerializedName("message") val message: String)`

When I debug below code

  ```
 is NetworkResponse.ServerError -> {
                      result?.let {
                          errorResponse.postValue(it.body)
                      }
                  }

```

It always response like below

```
ServerError(body=ErrorImages(message=null), code=403, headers=date: Wed, 03 Feb 2021 04:37:37 GMT
content-type: application/json
content-length: 42
x-amzn-requestid: b500109b-6fca-4d8c-a9c5-f791b4a21f47
x-amzn-errortype: MissingAuthenticationTokenException
x-amz-apigw-id: aJtGxEpZSQ0Flfg=
)
```

I need to show message, but I am not understanding why message always null

**Comment by haroldadmin** [comment]
The problem seems to be in your JSON deserializer. From the `@SerializedName` annotation, I guess you are using Gson. Can you confirm if you have added [GsonConverterFactory](https://github.com/square/retrofit/tree/master/retrofit-converters/gson) to your Retrofit instance?

**Comment by panchalamitr** [comment]
Hi, first of all thank you so much for immediate response,

Yes I have added, Below is my code

```
@Singleton
    @Provides
    fun provideRetrofit(
        gson: Gson,
        networkResponseAdapterFactory: NetworkResponseAdapterFactory
    ): Retrofit.Builder {
        return Retrofit.Builder()
            .baseUrl(Constants.BASE_URL)
            .addCallAdapterFactory(networkResponseAdapterFactory)
            .addConverterFactory(GsonConverterFactory.create(gson))
            .client(okHttp)
    }
```

If Gson is not working, then it should also not work with SuccessResponse right, SuccessResponse is working fine and it is more complex then ErrorResponse.

**Comment by panchalamitr** [comment]
I have used your library in my below code

`https://github.com/panchalamitr/SG_Live_Traffic_Demo`

**Comment by haroldadmin** [comment]
In your DI setup, you configure Gson to [exclude fields without `@Expose` annotation](https://github.com/panchalamitr/SG_Live_Traffic_Demo/blob/b827b08ee3653c7739ecc271b0e933589536a716/app/src/main/java/com/panchalamitr/sglivetraffic/di/RetrofitInstance.kt#L28)

In your `ErrorTrafficImages` class, the `message` property [does not have `@Expose`](https://github.com/panchalamitr/SG_Live_Traffic_Demo/blob/b827b08ee3653c7739ecc271b0e933589536a716/app/src/main/java/com/panchalamitr/sglivetraffic/model/ErrorTrafficImages.kt#L6)

Try adding `@Expose` to the property, or remove `excludeFieldsWithoutExposeAnnotation()` modifier on Gson.

**Comment by panchalamitr** [comment]
Thank you so much for your support :)

I have first used my code without @Expose, but with that also code was not working,

I have removed excludeFieldsWithoutExposeAnnotation() as well as all Expose annotation from all data,

But still I am getting same error.

**Comment by haroldadmin** [comment]
I cloned your repository to try it on my system. 

I added an OkHttp interceptor to simulate an API response with error code 403, and body set to `{"message":"Missing Authentication Token"}`. 

The response was deserialized correctly. 

Here's the response I caught in the debugger:
![image](https://user-images.githubusercontent.com/24315306/107116771-8d03fb00-689b-11eb-8f6a-4e5405c682d3.png)

Here's the interceptor code from `RetrofitInstance.kt` file:
```kotlin
private val okHttp: OkHttpClient
    get() {
        val loggingInterceptor = LoggingInterceptor.Builder()
            .setLevel(Level.BASIC)
            .log(Log.VERBOSE)
            .build()
        return OkHttpClient.Builder()
            .addInterceptor(loggingInterceptor)
            .addInterceptor { chain ->
                Response.Builder()
                    .request(chain.request())
                    .code(403)
                    .protocol(Protocol.HTTP_1_1)
                    .message("unauthorized")
                    .body("""
                        { 
                            "message": "Missing Authentication Token" 
                        }
                        """
                        .trimIndent()
                        .toResponseBody("application/json".toMediaType()))
                    .build()
            }
            .build()
    }
```

It seems like the library is working correctly.

**Comment by panchalamitr** [comment]
I am closing this issue, as it is working perfect.

**Comment by iyashamihsan** [comment]
im also getting null in ServerError after API call 
@panchalamitr  can you tell me how do you solve this issue ?

**Comment by panchalamitr** [comment]
Hi @iyashamihsan, after getting some comments to this issue, I have tested my code again, after few days and surprisingly it started to works so I have marked as closed. Still don’t have idea why I was getting null

**Comment by haroldadmin** [comment]
If you could provide a sample project which consistently reproduces this issue, I'd be very happy to take a look at it @iyashamihsan
