### ISSUE TITLE
NetworkResponse Error Managing

### ISSUE THREAD

**Issue by allanserre** [haroldadmin/NetworkResponseAdapter#36]
When i get a "204 No content" response from my API , NetWorkResponse consider it as a server error. But it should be a SUCCESS response. As describe in the ReadMe a response code 2xx is consider as successfull.

**Comment by haroldadmin** [comment]
If your API response contains no body, please use `Unit` as the success body type.

```kotlin
interface DocsApi {
  @Get("/docs")
  suspend fun getDocs(): NetworkResponse<Unit, ErrorType>
}
```

This has been documented [here](https://haroldadmin.github.io/NetworkResponseAdapter/special-cases/).

**Comment by allanserre** [comment]
Thank for your an

**Comment by haroldadmin** [comment]
I think it just means that docs need to be better :sweat_smile:
