### ISSUE TITLE
NetworkResponseAdapterFactory crashes on unhandled response types

### ISSUE THREAD

**Issue by RobertLK** [haroldadmin/NetworkResponseAdapter#38]
The check here: https://github.com/haroldadmin/NetworkResponseAdapter/blob/master/src/main/kotlin/com/haroldadmin/cnradapter/NetworkResponseAdapterFactory.kt#L14 will cause a crash if consumer uses other response types that can be handled by different factories but aren't parameterised (such as Completeable type with RxJava adapter). Retrofit's convention here is to return null when a factory realises it can't handle the response type so other Factories may try. This should therefore be the behaviour for unparameterised types as well as types that aren't `NetworkResponse`.

Workaround is to make sure `NetworkResponseAdapterFactory` is always the last adapter in the list but this shouldn't be required.

**Comment by haroldadmin** [comment]
Thanks for catching this. I'll try to get a fix out for this soon, but can't promise an ETA.
