### ISSUE TITLE
ResponseHandler should allow to pass our own converter

### ISSUE THREAD

**Issue by javaboboApp** [haroldadmin/NetworkResponseAdapter#39]
ResponseHandler should allow to pass our own converter NullOnEmptyConverterFactory extends Converter.Factory.
I am not able to deal with reponses 204 using GET method and empty body because of this.

**Comment by haroldadmin** [comment]
If your response has an empty body, use the `Unit` as the success response type. See [here](https://haroldadmin.github.io/NetworkResponseAdapter/special-cases/)

**Comment by javaboboApp** [comment]
That is true but what happens when api returns sometimes 204 and other times an json object. We get an error...

**Comment by javaboboApp** [comment]
It would be better if you add another response such us Success (header..) without body and other with body, so developer have control about this kind of situations.

**Comment by haroldadmin** [comment]
I'm not sure what's the best way to handle your usecase. If your API response is unpredictable, it might be best to not use the `NetworkResponse` class as its return type. You could instead return an `Any` from your API interface, and perform checks at runtime to identify the type of response.

Response converter factories usually don't accept other response converters as input parameters. If you have multiple types of response converters, you should add them to Retrofit directly.

```kotlin
Retrofit.Builder()
    .addCallAdapterFactory(...)
    .addCallAdapterFactory(...)
    .addCallAdapterFactory(...)
    .addCallAdapterFactory(NetworkResponseAdapterFactory())
    .build()
```

**Comment by javaboboApp** [comment]
umm I see yeah is another way to solve this issue but what I have done in this case is add a new type of success response called: SuccessWithEmptyBody so I just have modified library to support this kind of situation.
