### ISSUE TITLE
How To Handle Error Response ?

### ISSUE THREAD

**Issue by rahat14** [haroldadmin/NetworkResponseAdapter#45]
NetworkResponse<LoginResponse, ErrorResponse> . where to acess the ErrorResponse model i created 
 when (person) {
        is NetworkResponse.Success -> {
            // Handle successful response
        }
        is NetworkResponse.ServerError -> {
            // Handle server error
        }
        is NetworkResponse.NetworkError -> {
            // Handle network error
        }
        is NetworkResponse.UnknownError -> {
            // Handle other errors
        }

**Comment by haroldadmin** [comment]
Hi, as stated in the [documentation](https://haroldadmin.github.io/NetworkResponseAdapter), the `ServerError` subtype of `NetworkResponse` contains the deserialized error body from the server (`ErrorResponse` in your case). You can access it using the [`body`](https://github.com/haroldadmin/NetworkResponseAdapter/blob/adb4dd6f6c990802c014d8a3bc12aa3b9f4002c0/src/main/kotlin/com/haroldadmin/cnradapter/NetworkResponse.kt#L38) property:

```kotlin
when (person) {
  // ... other cases
  is NetworkResponse.ServerError -> {
    val errorResponse = person.body
  }
}
```

**Comment by rahat14** [comment]
@haroldadmin  i am sorry i found out that  . cant i use this library without suspend functiuon like this ->
   @FormUrlEncoded
    @POST("login")
     fun loginUser(
        @Field("phone") phone: String,
        @Field("password") password: String
    ): NetworkResponse<LoginResponse, ErrorResponse>

**Comment by haroldadmin** [comment]
The library is based on Coroutines. If you can't use suspend functions, you could try using the `Deferred` return type. `Deferred` is Kotlin's Future/Promise type that completes with a value eventually.

```kotlin
@FormUrlEncoded
@Post("login")
fun loginUser(
  @Field("phone") phone: String,
  @Field("password") password: String
): Deferred<NetworkResponse<LoginResponse, ErrorResponse>>
```

**Comment by rahat14** [comment]
OK. Thnx Closing This Now
