### ISSUE TITLE
Retrofit mock

### ISSUE THREAD

**Issue by croccio** [haroldadmin/NetworkResponseAdapter#49]
How can i mock the response with retrofit mock? i did something like this but i get NetworkResponse$NetworkError cannot be cast to LoginResponseSuccess/Error

`
class MockService(val delegate: BehaviorDelegate<Service>) : Service {

    override suspend fun login(body: LoginRequest):
            NetworkResponse<LoginResponseSuccess, LoginResponseError> {

        var response: NetworkResponse<LoginResponseSuccess, LoginResponseError>? = null

        if (body.username == "401@error.er") {
            response = NetworkResponse.ServerError<LoginResponseError>(
                getResponse(R.raw.login_response_error_401),
                code = 401
            )
        } else {
            response = NetworkResponse.Success<LoginResponseSuccess>(
                getResponse(R.raw.login_response_success),
                code = 200
            )
        }

        return delegate.returningResponse(response).login(body)
    }
`

**Comment by haroldadmin** [comment]
I'm not sure what the `BehaviorDelegate` does, but the rest of the code sample you provided looks okay. Can you share more details about the delegate or a small sample project to reproduce this problem?

**Comment by croccio** [comment]
thanks, i resolved it i'll write here solution so if someone has the same problem can fix it. You have to return directly the NetworkResponse. so the new code looks like this:


`
override suspend fun login(body: LoginRequest):
        NetworkResponse<LoginResponseSuccess, LoginResponseError> {

    var response: NetworkResponse<LoginResponseSuccess, LoginResponseError>? = null

    if (body.username == "401@error.er") {
        response = NetworkResponse.ServerError<LoginResponseError>(
            getResponse(R.raw.login_response_error_401),
            code = 401
        )
    } else {
        response = NetworkResponse.Success<LoginResponseSuccess>(
            getResponse(R.raw.login_response_success),
            code = 200
        )
    }

    **return response**
}`
