### ISSUE TITLE
List<T> as Success body 

### ISSUE THREAD

**Issue by vasskob** [haroldadmin/NetworkResponseAdapter#5]
Hello. What about handling List of items in success body response like 
suspend fun getEntitys(): NetworkResponse<List<Entity>, ErrorResponse>

**Comment by haroldadmin** [comment]
Hello! This is already supported and works well. For an illustration you can check [this file](https://github.com/haroldadmin/MoonShot/blob/b48a67770c4eea36a30dc020642bd1d207a50307/spacex-api-wrapper/src/main/java/com/haroldadmin/spacex_api_wrapper/launches/LaunchesService.kt#L25) in another project of mine.

This library does not handle serialization/deserialization of the responses. It delegates that responsibility to Retrofit itself.
