### ISSUE TITLE
How to run this source code in Android Studio???

### ISSUE THREAD

**Issue by hmshohrab** [haroldadmin/NetworkResponseAdapter#54]
How to run this source code in Android Studio???? 
 please help

**Comment by haroldadmin** [comment]
Can you describe your issue in more detail?

If your question is about how to install this library in an Android project, follow the instructions in the [README](https://github.com/haroldadmin/networkresponseadapter/blob/master/README.md):
1. Add Jitpack to your root level `build.gradle` file:
```groovy
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
```
2. Add a dependency for this library in your app module:
```groovy
dependencies {
    implementation "com.github.haroldadmin:NetworkResponseAdapter:(latest-version)"
}
```

If your question is about how to get the project setup for development/contribution in an IDE, then just clone the repository and open it with IntelliJ. It's a regular Kotlin project, and has no Android specific code. You don't need Android Studio to work with this. IntelliJ is sufficient.

**Comment by Sanat-Shukla** [comment]
@haroldadmin getting:
Failed to resolve: com.github.haroldadmin:NetworkResponseAdapter:5.0.0-alpha01
Failed to resolve: com.github.haroldadmin:NetworkResponseAdapter:4.2.2

**Comment by haroldadmin** [comment]
Have you added the Jitpack repository to your `build.gradle` file?

```groovy
allprojects {
    repositories {
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by Sanat-Shukla** [comment]
Yes @haroldadmin

**Comment by Sanat-Shukla** [comment]
@haroldadmin Need to add this into the settings.gradle. allProjects{} block is removed from the updated version of gradle. It's working fine now with the settings.gradle.

**Comment by haroldadmin** [comment]
I didn't know that `allProjects` config block is removed from Gradle. I can't find the release notes or a blog post on this change. Can you please share any resource containing this news? I'd like to update the README file with the correct instructions.

**Comment by Sanat-Shukla** [comment]
@haroldadmin Got the details from the stackoverflow: https://stackoverflow.com/a/69794803/2024527

**Comment by Sanat-Shukla** [comment]
@haroldadmin Got the details from the stackoverflow: https://stackoverflow.com/a/69794803/2024527
Don't know about official doc but it's working with the settings.gradle and having issue in allProjects{}.

Working solution:

```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by haroldadmin** [comment]
Closing this due to lack of response from OP
