### ISSUE TITLE
Adding NetworkResponseAdapterFactory to your Retrofit client in Java

### ISSUE THREAD

**Issue by sivansundar** [haroldadmin/NetworkResponseAdapter#61]
Hey @haroldadmin! 

First of all, sweet library. Makes things very standardized and thats a win. 

Been using this in my side projects for a while now and its great! One of my project is in migration to Kotlin and codebase is in transition so there are some files/modules written in Java. 

I was trying to add the NetworkResponseAdapterFactory to my RetrofitClient (written in Java) but unfortunately this doesn't seem to work. Throws an error saying incorrect type and even if I try casting the object, there is no luck. I was wondering if there is a workaround for this in Java for the time being.

Sample code for reference.

```
        return new Retrofit.Builder()
                .baseUrl(BuildConfig.BASE_URL)
                .addCallAdapterFactory(RxJava3CallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .addCallAdapterFactory(NetworkResponseAdapterFactory())
                .client(httpClient) 
```

Wondering if there is a Java equivalent of adding the NetworkResponseAdapterFactory() as a call adapter factory.

Thanks 😄

**Comment by haroldadmin** [comment]
Hey, I'm glad you find the project useful!

I haven't tested the library for Java compatibility. I imagine it's going to be pretty difficult, given that it uses Kotlin features extensively (sealed classes, coroutines, etc.).

That being said, I reproduced the issue you reported. Java does not recognize `NetworkResponseAdapterFactory()` as a valid `CallAdapter.Factory`. 

A short workaround is to use the delegation pattern:

```java
class DelegateNetworkResponseAdapterFactory extends CallAdapter.Factory {

  @Override
  public CallAdapter<?, ?> get(Type returnType, Annotation[] annotations, Retrofit retrofit) {
    var factory = new NetworkResponseAdapterFactory();
    return factory.get(returnType, annotations, retrofit);
  }
}

...

new Retrofit.Builder()
  .baseUrl(BuildConfig.BASE_URL)
  .addCallAdapterFactory(RxJava3CallAdapterFactory.create())
  .addConverterFactory(GsonConverterFactory.create())
  .addCallAdapterFactory(new DelegateNetworkResponseAdapterFactory())
  .client(httpClient) 
```

I don't know if this fixes all the compatibility issues with Java, but I can confirm that the above code snippet compiles.

**Comment by sivansundar** [comment]
Thanks for the quick response @haroldadmin. Will try this out for and let you know how it goes. The idea is to eventually pivot to kotlin completely which could make things so much more easier. Thanks once again.

**Comment by haroldadmin** [comment]
Closing this issue. Please reopen it if you need more help.
